version: "3"
services:
  app:
    image: alexbenko/cam:latest
    volumes:
      - ./audio:/audio
      - ./recordings:/recordings
    environment:
      app_title: Watch Cam
      PORT: 5000
      save_images: True
    ports:
      - "5000:5000"
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    command: python3 main.py
    restart: unless-stopped
    env_file: .env
  mongo:
    image: arm64v8/mongo
    env_file: .env