version: "3"
services:
  app:
    image: alexbenko/cam:latest
    volumes:
      - ./audio:/audio
    environment:
      appTitle: Watch Cam
      PORT: 5000
    ports:
      - "5000:5000"
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    command: python3 main.py
    restart: unless-stopped