version: "3"
services:
  app:
    image: alexbenko/cam:latest
    volumes:
      - ./audio:/audio
      - ./recordings:/recordings
      - ./.env:/.env
    env_file: .env
    environment:
      app_title: Watch Cam
      PORT: 5000
      save_images: "False"
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    command: python3 main.py
    depends_on:
      - mongodb
  mongodb:
    image: arm64v8/mongo:4.4
    logging:
      driver: none
    env_file: .env
    volumes:
      - ./data2/mongo:/data/db
      - ./.env:/.env