version: "3"
services:
  app:
    image: alexbenko/threaded_cam:latest
    volumes:
      - ./audio:/audio
      - ./recordings:/recordings
      - ./.env:/.env
      - ./data:/data
      - ./static:/static
    env_file: .env
    environment:
      app_title: Watch Cam
      PORT: ${PORT}
      PYTHONUNBUFFERED: 1 #for some reason docker suppresed any prints beyond the start up ones, this enables prints in the docker container
      local_access_only: "True"
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      PHONE_NUMBER: ${PHONE_NUMBER}
      save_images: "True"
      CARRIER: ${CARRIER}
      TZ: ${TZ}
    ports:
      - "${PORT}:${PORT}"
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
    command: python3 main.py